// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_field

/// KitchenSinkClient, an autogenerated Dart Client.
library kitchen_sink_client;

export 'src/kitchen_sink_client.dart';
export 'src/endpoint.dart';
export 'src/request.dart';
export 'src/resources.dart';
