name: new_route_hooks
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  dart_frog_gen: ^0.3.2
  mason: ">=0.1.0-dev.49 <0.1.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

dependency_overrides:
  dart_frog_gen:
    path: ../../../packages/dart_frog_gen
