name: dart_frog_server_hooks
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dart_frog:
    git:
      url: https://github.com/VeryGoodOpenSource/dart_frog
      path: packages/dart_frog
  mason: ">=0.1.0-dev <0.1.0"
  path: ^1.8.1
