{{> generated_header }}

/// {{client.packageName.pascalCase()}}, an autogenerated Dart Client.
library {{client.packageName.snakeCase()}};

export 'src/{{client.packageName.snakeCase()}}.dart';
export 'src/endpoint.dart';
export 'src/request.dart';
export 'src/resources.dart';
