name: dart_frog_dev_server

on:
  pull_request:
    paths:
      - ".github/workflows/dart_frog_dev_server.yaml"
      - "bricks/dart_frog_dev_server/hooks/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dart_frog_dev_server.yaml"
      - "bricks/dart_frog_dev_server/hooks/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: bricks/dart_frog_dev_server/hooks
      analyze_directories: .
      report_on: pre_gen.dart
