name: dart_frog

on:
  pull_request:
    paths:
      - ".github/workflows/dart_frog.yaml"
      - "packages/dart_frog/lib/**"
      - "packages/dart_frog/test/**"
      - "packages/dart_frog/pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/dart_frog.yaml"
      - "packages/dart_frog/lib/**"
      - "packages/dart_frog/test/**"
      - "packages/dart_frog/pubspec.yaml"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: packages/dart_frog

  pana:
    defaults:
      run:
        working-directory: packages/dart_frog

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: dart-lang/setup-dart@v1

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana
      - name: Verify Pub Score
        run: ../../tool/verify_pub_score.sh
