name: examples/todos

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "examples/todos/pubspec.yaml"
      - "examples/todos/routes/**"
      - "examples/todos/lib/**"
      - "examples/todos/test/**"
      - "examples/todos/packages/**/pubspec.yaml"
      - "examples/todos/packages/**/lib/**"
      - "examples/todos/packages/**/test/**"
      - "examples/todos/packages/**/e2e/**"
      - ".github/workflows/examples_todos.yaml"
      - "packages/dart_frog/lib/**"
      - "packages/dart_frog/pubspec.yaml"
      - "packages/dart_frog_cli/lib/**"
      - "packages/dart_frog_cli/pubspec.yaml"
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: examples/todos
      analyze_directories: "routes test"
      report_on: "routes"

  docker:
    uses: ./.github/workflows/.docker_tests.yaml
    with:
      setup: rm pubspec_overrides.yaml && dart pub global activate --source path ../../packages/dart_frog_cli
      working_directory: examples/todos

  todos_data_source:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: examples/todos/packages/todos_data_source

  in_memory_todos_data_source:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: examples/todos/packages/in_memory_todos_data_source
