name: publish_dart_frog_auth

on:
  push:
    tags:
      - "dart_frog_auth-v*.*.*"
  workflow_dispatch:

jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_pub_publish.yml@v1
    with:
      working_directory: "packages/dart_frog_auth"
    secrets:
      pub_credentials: ${{ secrets.PUB_CREDENTIALS }}
