name: update_cli_bundles

on:
  schedule:
    # weekly on mondays at 8 am utc
    - cron: '0 8 * * 1'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - name: Install mason
        run: dart pub global activate mason_cli

      - name: Bump templates
        run: tool/generate_bundles.sh

      - name: Config Git User
        run: |
          git config user.name VGV Bot
          git config user.email vgvbot@users.noreply.github.com

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.2
        with:
          base: main
          branch: feat/bump-template-bundles
          commit-message: "feat: update cli bundles"
          title: "feat(dart_frog_cli): update cli bundles"
          body: Please squash and merge me!
          labels: bot
          author: VGV Bot <vgvbot@users.noreply.github.com>
          assignees: vgvbot
          committer: VGV Bot <vgvbot@users.noreply.github.com>
